<?php

$template = match ($_SERVER['REQUEST_URI']) {
    '/' => 'pages/index.php',
    '/alexandr-andreevich' => 'pages/about.php',
    '/blog' => 'pages/blog/index.php',
    '/blog/students' => 'pages/blog/2019/students.php',
    '/blog/koronavirus' => 'pages/blog/2020/koronavirus.php',
    '/blog/planning' => 'pages/blog/2020/planning.php',
    '/blog/books-2020' => 'pages/blog/2020/books-2020.php',
    '/blog/podcasts' => 'pages/blog/2021/podcasts.php',
    '/blog/movies-imdb' => 'pages/blog/2021/movies-imdb.php',
    '/blog/run' => 'pages/blog/2021/run.php',
    '/blog/black-lines' => 'pages/blog/2021/black-lines.php',
    '/blog/site-update' => 'pages/blog/2021/site-update.php',
    '/blog/home-bay' => 'pages/blog/2021/home-bay.php',
    '/blog/new-super-heroes' => 'pages/blog/2021/new-super-heroes.php',
    '/blog/seats-in-the-trolleybus' => 'pages/blog/2021/seats-in-the-trolleybus.php',
    '/blog/people-without-food'=> 'pages/blog/2021/people-without-food.php',
    '/blog/books-2021'=> 'pages/blog/2021/books-2021.php',
    '/blog/run-2018-2020' => 'pages/blog/2021/run-2018-2020.php',
    '/blog/run-2021' => 'pages/blog/2021/run-2021.php',
    '/blog/total-2021' => 'pages/blog/2021/total-2021.php',
    '/blog/kinopoisk-250' => 'pages/blog/2021/kinopoisk-250.php',
    '/blog/seo' => 'pages/blog/2022/seo.php',
    '/blog/world-cup-2022' => 'pages/blog/2022/world-cup-2022.php',
    '/blog/run-2022' => 'pages/blog/2022/run-2022.php',
    '/blog/books-2022' => 'pages/blog/2022/books-2022.php',
    '/blog/total-2022' => 'pages/blog/2022/total-2022.php',
    '/blog/car-in-winter' => 'pages/blog/2023/car-in-winter.php',
    '/portfolio' => 'pages/portfolio.php',
    '/travels' => 'pages/travels.php',
    '/projects' => 'pages/projects.php',
    '/library', '/library?show_type=short-list', '/library?show_type=full-list' => 'pages/library.php',
    '/stats' => 'pages/stats.php',
    '/site' => 'pages/site.php',
    '/sitemap' => 'pages/sitemap.php',
    '/load-book' =>'ajax/load-book.php',
    default => 'errors/404.php'
};

echo renderPage($template);